### ISSUE TITLE
Docker redis failing to connect

### ISSUE THREAD

**Issue by WardPearce** [mCaptcha/mCaptcha#112]
Greetings,
After the most recent update my docker container for mcaptcha all of a sudden stopped working due to redis not being able to connect, I haven't changed anything in the docker compose before the update. Everything was working fine

```
Version: 0.1.0 commit: 9e77eec6576558e5440bd4d00f0947c62cffae1c

 INFO  mcaptcha::settings > Loading config file from /etc/mcaptcha/config.toml

 INFO  mcaptcha::data     > Initializing credential manager

 INFO  sqlx::postgres::notice > relation "_sqlx_migrations" already exists, skipping

thread 'main' panicked at /usr/local/cargo/git/checkouts/libmcaptcha-3667a1c790960085/6bc0d11/src/redis/mod.rs:46:22:

called `Result::unwrap()` on an `Err` value: Connection refused (os error 111)
```

**Comment by realaravinth** [comment]
Hi,

Apologies, I'm in the process of upgrading dependencies across multiple repositories, and I that broke your installation.  

I'll start tagging releases after the update is finished, so that we can this in the future. :sweat:

**Comment by WardPearce** [comment]
> Hi,
> 
> Apologies, I'm in the process of upgrading dependencies across multiple repositories, and I that broke your installation.
> 
> I'll start tagging releases after the update is finished, so that we can this in the future. 😓

awesome, no worries 👍

**Comment by WardPearce** [comment]
if you could close this issue once resolved also so i can track it thank u
