### ISSUE TITLE
Question: How to reset mcpatcha widget?

### ISSUE THREAD

**Issue by Flajt** [mCaptcha/mCaptcha#123]
Hello, first of all thank you for this cool application, I'm currently using it in the development of a side project of mine.

I've got one question, right now I'm submitting all my data not via form but via a post request to my own webserver which handles the rest. For this I extract the token from the text input field. But after my request is successfull I would like to reset the checked state of the widget. Is that possible if I don't use a form?

(Currently you need to either refresh the page, which would have done if there wouldn't be some state I need to display, or click it again to reset it)

**Comment by realaravinth** [comment]
When you you don't use a form, do mean you use JavaScript to upload data to the server? 

`@mcaptcha/core-glue` JavaScript library is responsible for communicating with the widget. Specifically, [`handle`](https://github.com/mCaptcha/glue/blob/d66d22f6c869c8d3e49efabff7078f15a493e9b8/packages/core/src/index.ts#L93) listens for messages from the widget and passes to a higher level (web framework variants that we have) library to inject into the form.

A custom implementation of the core-glue library will allow you to not only retrieve the token efficiently but also reset the widget. Resetting, like you say, will have to be done by page refresh only. Having two-way communication between the protected page and the widget can be messy, so I want to avoid that :sweat_smile: 

Feel free to ignore: I might be missing something, but can you please explain why you would want to reset the widget? Usually, the visitor will be advanced to the protected resource, after successful CAPTCHA validation. But the case you describe requires the visotir to solve the CAPTCHA again.

**Comment by realaravinth** [comment]
Thanks for explaining! I think I understand it, if you want to show the CAPTCHA to the user again, then removing the iframe with JavaScript and creating it again when needed also works?

**Comment by Flajt** [comment]
Might be worth a shot, I will try this in the next couple of days. Thank you

**Comment by Flajt** [comment]
Seems to do the trick, thanks again.
