### ISSUE TITLE
Tag the docker image

### ISSUE THREAD

**Issue by L3o-pold** [mCaptcha/mCaptcha#126]
We only have latest and master dockerhub tag. Maybe because the git project have no tag/release yet. Could be nice to avoid the usage of the :latest docker tag.

**Comment by realaravinth** [comment]
Hi,
Thanks for filing this issue. I intend on setting up a release procedue by mid-January. 

I wasn't sure if mCaptcha warranted a release yet, but I accidentally broke mCaptcha/cache and had to rust to make a release to avoid such situations in the future ([which, I'm sure you are aware](https://github.com/mCaptcha/cache/issues/12) :sweat_smile:).

Setting up periodic release cyles will be good, I think. But I have no experience in this area, so I'd appreciate any advice that you might have :)

**Comment by ZeroAurora** [comment]
A good way to tag is to [semantic version](https://semver.org/) it.

**Comment by realaravinth** [comment]
I apologize for the delay, this is my first time releasing software so it took a while for me to automate the build process and everything. Going forward, tagged images will be automatically published on every release (#142).

**Comment by binaryfire** [comment]
@realaravinth This is great, thank you!
