### ISSUE TITLE
Many console errors when solving the captcha

### ISSUE THREAD

**Issue by SebastianGode** [mCaptcha/mCaptcha#134]
I get the following errors in the console when solving the captcha:
```
Uncaught (in promise) TypeError: Cannot mix BigInt and other types, use explicit conversions
```

This originates from the following line:
https://github.com/mCaptcha/mCaptcha/blob/master/templates/widget/index.ts#L97

![image](https://github.com/mCaptcha/mCaptcha/assets/70581801/39a89901-a0d2-405c-b30e-8951602eac7b)

**Comment by binaryfire** [comment]
I'm getting this too
