### ISSUE TITLE
`Difficulty factor should increase with level` when using Easy mode of setting New Sitekey

### ISSUE THREAD

**Issue by GamePlayer-8** [mCaptcha/mCaptcha#151]
Good morning,

I've got a problem/bug with mCaptcha UI, where I couldn't add New Site Key using Easy Mode.

The error what I'm getting is `Difficulty factor should increase with level` with a 400 Bad request from `https://captcha.chimmie.k.vu/api/v1/mcaptcha/add/easy`.

My parameters:
 - Description: `Bruteforce Protection`
 - Average Traffic of your website: `2000
 - Maximum traffic that your website can handle: `10000`
 - Traffic that broke your website(Optional): `20000`

Version: `v0.1.0-59e339f2`
Installation method: using Docker compose.

**Comment by realaravinth** [comment]
Hello o/

Thanks for creating an issue, this one is on me. I did a typo while porting [the configuration file](https://github.com/mCaptcha/mCaptcha/blob/master/config/default.toml) into the corresponding [list of environment variables](https://github.com/mCaptcha/mCaptcha/blob/master/.env.docker-compose) for use in Docker deployments. The difficulty factor for the "broke my site" level is greater than the "peak traffic" level, which is causing the error.

I'm uploading a patch in a bit, which should fix this issue.
