### ISSUE TITLE
High CPU / Postgres Database usage after running for a longer while when idle / no requests are made.

### ISSUE THREAD

**Issue by GamePlayer-8** [mCaptcha/mCaptcha#154]
Good morning again,

There's an issue with CPU utilization for mCaptcha when it's idle. After an hour or two it goes from around 1% to 30% ~ 70%.

Here's an [mCaptcha Docker log](https://gist.chimmie.k.vu/GamePlayer-8/0cdf7d74e3ca4a91bbd9a7ee5a00066b).

Not sure what's happening exactly.

**Comment by realaravinth** [comment]
I'm unable to reproduce high CPU usage on my end. I used captcha configuration from your previous issue, left it idle for 2 minutes after successful verification and tried the widget. Everything seems to work fine.

I'll let the thing run for another 30 minutes and try again.

More logs will be helpful. Please set the following in `.env.docker-compose`:

```
RUST_LOG=trace
MCAPTCHA_debug=true
```

And kindly produce the logs for the database and cache as well (complete output of `docker-compose logs` )

**Comment by titnguyen** [comment]
Hi @GamePlayer-8 , have you resolve the issue?

**Comment by GamePlayer-8** [comment]
@titnguyen the issue was resolved on the matrix group if the issue came back, post the debug log of what's happening.

**Comment by titnguyen** [comment]
I created the issue https://github.com/mCaptcha/mCaptcha/issues/185. It seem not relates to your case since there are some requests are made in mine.
