### ISSUE TITLE
failed to load source for dependency `actix-web-codegen`

### ISSUE THREAD

**Issue by ChocoMilkWithoutSugar** [mCaptcha/mCaptcha#22]
I get this error running the docker-compose up -d command

``` => [frontend  7/15] RUN  yarn install && cd docs/openapi && yarn install                                                                                                                    61.8s 
 => [rust  2/15] WORKDIR /src                                                                                                                                                                 1.9s 
#0 47.95     Updating git repository `https://github.com/realaravinth/cache-buster`
#0 48.72     Updating git repository `https://github.com/mCaptcha/libmcaptcha`
#0 49.47     Updating git repository `https://github.com/realaravinth/actix-web`
#0 51.92 error: failed to get `actix-web-codegen` as a dependency of package `mcaptcha v0.1.0 (/src)`
#0 51.92
#0 51.92 Caused by:
#0 51.92   failed to load source for dependency `actix-web-codegen`
#0 51.92
#0 51.92 Caused by:
#0 51.92   Unable to update https://github.com/realaravinth/actix-web#950d1265
#0 51.92
#0 51.92 Caused by:
#0 51.92   object not found - no match for id (950d1265ee32f34efe6acb6663c56881ba1b489a); class=Odb (9); code=NotFound (-3)
------
failed to solve: executor failed running [/bin/sh -c cargo build --release]: exit code: 101
```

steps followed:
1. git clone https://github.com/mCaptcha/mCaptcha
2. cd mCaptcha
3. docker-compose up -d

**Comment by realaravinth** [comment]
I'm afraid this is going to take longer than anticipated. The original issue(`actix-web-codegen` dependency resolution failure) is resolved and code is compiling alright([verified by the build step in the CI](https://github.com/mCaptcha/mCaptcha/runs/6340940619?check_suite_focus=true#step:9:131)) but the tests are failing.

I haven't made any changes to the codebase apart from accommodating breaking dependencies, but the tests are failing from literally having too many tests([and trying to initialize a DB connection for every test](https://github.com/mCaptcha/mCaptcha/runs/6340940619?check_suite_focus=true#step:11:722)).

I have allocated another 5 days towards cleaning up the test suite to get the tests working again. Apologies for the delay.

**Comment by ChocoMilkWithoutSugar** [comment]
Can I help you with something?
I have never developed using Rust

**Comment by realaravinth** [comment]
Thank you for the offer, but I think I can handle this :)

**Comment by realaravinth** [comment]
Closing issue: Original cause solved, [pushed a hostfix](https://github.com/mCaptcha/mCaptcha/commit/a00823544ec7b3ff2788d02f704900439c0eeeef) to get the test suite working again. [Refactor underway](https://github.com/mCaptcha/mCaptcha/compare/db-abstract) for permanent fix of the test suite.


If you require help setting up mCaptcha, feel free to open an issue or contact me via any of the means listed on [the website](http://mcaptcha.org/contact) :)
