### ISSUE TITLE
production readiness and our effort to get something production ready

### ISSUE THREAD

**Issue by wzrdtales** [mCaptcha/mCaptcha#71]
First of all, thank you again for working on this library. I appreciate it that much b/c I planned to work on it for a very long time. The first time I wrote about it in 2015 on my old, now not existing blog https://web.archive.org/web/20210302100358/https://blog.wizardtales.com/2015/12/18/a-captchas-tale/, but I never found the time for it.

So thank you for your efforts :)

Now we finally were forced to look into it and found your solution aside from a few different implementations (just demos) and were happy to see a quite thought-through solution.

Next I want to highlight: This is not intended as advertising, but more our way of sharing it with you and the community. I have no doubt you and the community bring this module to production readiness as well at some point. So I want to encourage you, if you feel this is wrongly placed in your opinion, please go ahead and delete the issue. 

Continuing, now that we have run it in production, though, it became clear it is far too unstable to run production. We don't think that is really on your side of things but more on the general immaturity of rust as a whole. So we decided to write an own backend for processing pows in a different language with a toolset ready for production use. You can find it over here:

https://github.com/WizardTales/pow-node

You're very welcome to utilize the code, as well as ignoring it :)

Thank you again for your efforts!

**Comment by wzrdtales** [comment]
for sure :)

**Comment by realaravinth** [comment]
It's [done](https://github.com/mCaptcha/contrib)

**Comment by wzrdtales** [comment]
:+1: We also evaluate using a POW for our https://github.com/wzrdtales/secure-passwords/ auth (https://medium.com/@wzrdtales/your-passwords-are-at-risk-why-ssl-is-not-enough-and-how-to-solve-it-75356a3fd762) since it allows lower cost on the server side.
